checkout v2

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -29,10 +29,28 @@ jobs:
     runs-on: ubuntu-20.04
     steps:
       - 
-        name: "Checkout  source code"
-        uses: actions/checkout@v1
+        name: "Checkout source code"
+        uses: actions/checkout@v2
         with:
           fetch-depth: 1
+      - 
+        name: Check existing tags
+        run: |
+          set +e
+          RECREATE_TAGS=${{ github.event.inputs.forceRecreateTags }}
+          VERSION=${{ github.event.inputs.version }}
+          EXISTING_TAG=$(git ls-remote --exit-code origin refs/tags/${VERSION})
+          if [[ -n ${EXISTING_TAG} ]]; then
+            if [[ ${RECREATE_TAGS} == "true" ]]; then
+              echo "[INFO] Removing tag for ${VERSION} version. New tag will be recreated during release."
+              git push origin :$VERSION
+            else
+              echo "[ERROR] Cannot proceed with release - tag ${EXISTING_TAG} already exists."
+              exit 1
+            fi
+          else
+            echo "[INFO] No existing tags detected for $VERSION"
+          fi
       -
         name: "Set up QEMU"
         uses: docker/setup-qemu-action@v1
@@ -82,24 +100,6 @@ jobs:
         uses: actions/checkout@v2
         with:
           fetch-depth: 0
-      - 
-        name: Check existing tags
-        run: |
-          set +e
-          RECREATE_TAGS=${{ github.event.inputs.forceRecreateTags }}
-          VERSION=${{ github.event.inputs.version }}
-          EXISTING_TAG=$(git ls-remote --exit-code origin refs/tags/${VERSION})
-          if [[ -n ${EXISTING_TAG} ]]; then
-            if [[ ${RECREATE_TAGS} == "true" ]]; then
-              echo "[INFO] Removing tag for ${VERSION} version. New tag will be recreated during release."
-              git push origin :$VERSION
-            else
-              echo "[ERROR] Cannot proceed with release - tag ${EXISTING_TAG} already exists."
-              exit 1
-            fi
-          else
-            echo "[INFO] No existing tags detected for $VERSION"
-          fi
       -
         name: "Set up QEMU"
         uses: docker/setup-qemu-action@v1
@@ -148,7 +148,7 @@ jobs:
     steps:
       -
         name: "Checkout source code"
-        uses: actions/checkout@v1
+        uses: actions/checkout@v2
         with:
           fetch-depth: 0
       - 
@@ -206,7 +206,7 @@ jobs:
     steps:
       -
         name: "Checkout source code"
-        uses: actions/checkout@v1
+        uses: actions/checkout@v2
         with:
           fetch-depth: 0
       -
